configuration: Release

# restore NuGet packages before running MSBuild
before_build: 
  - nuget restore Ease-L.sln
  
# package Web Application project for Web Deploy
build:
  verbosity: minimal
  publish_wap: true
  
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - projectA\libs
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'