configuration: Release

# restore NuGet packages before running MSBuild
before_build: 
  - nuget restore Ease-L.sln
  
# package Web Application project for Web Deploy
build:
  verbosity: minimal
  publish_wap: true
  
cache:
- packages -> **\packages.config

deploy:
- provider: Environment
  name: appvey deploy
  site_name: www.ease-l.xyz